// ============================================================
// MOCK DATA — replaces all Base44 backend calls
// ============================================================

export const MOCK_USER = {
  id: "user-1",
  email: "surafelkaleab68@gmail.com",
  full_name: "Surafel Kaleab",
  role: "admin",
  bio: "Passionate learner and developer.",
  location: "Addis Ababa, Ethiopia",
  website: "https://surafel.dev",
  company_name: "",
  reputation_score: 4.7,
  total_ratings: 12,
  verification_status: "verified",
};

export const MOCK_COURSES = [
  {
    id: "c1",
    title: "Full-Stack Web Development",
    description:
      "Master modern web development with React, Node.js, and databases. Build real-world projects from scratch.",
    instructor_email: "demo@skillforge.com",
    instructor_name: "Sarah Chen",
    category: "programming",
    difficulty: "intermediate",
    status: "published",
    enrollment_count: 45,
    rating: 4.8,
    tags: [],
    created_date: "2026-03-01",
  },
  {
    id: "c2",
    title: "UI/UX Design Fundamentals",
    description:
      "Learn the principles of great design. From wireframes to high-fidelity prototypes using Figma.",
    instructor_email: "demo@skillforge.com",
    instructor_name: "Alex Rivera",
    category: "design",
    difficulty: "beginner",
    status: "published",
    enrollment_count: 32,
    rating: 4.6,
    tags: [],
    created_date: "2026-03-02",
  },
  {
    id: "c3",
    title: "Data Science with Python",
    description:
      "Dive into data analysis, machine learning, and visualization using Python, Pandas, and Scikit-learn.",
    instructor_email: "demo@skillforge.com",
    instructor_name: "Dr. James Park",
    category: "science",
    difficulty: "advanced",
    status: "published",
    enrollment_count: 28,
    rating: 4.9,
    tags: [],
    created_date: "2026-03-03",
  },
  {
    id: "c4",
    title: "Digital Marketing Strategy",
    description:
      "Master SEO, social media marketing, content strategy, and paid advertising campaigns.",
    instructor_email: "demo@skillforge.com",
    instructor_name: "Maya Johnson",
    category: "marketing",
    difficulty: "beginner",
    status: "published",
    enrollment_count: 56,
    rating: 4.5,
    tags: [],
    created_date: "2026-03-04",
  },
  {
    id: "c5",
    title: "Business Leadership",
    description:
      "Develop essential leadership skills, team management, and strategic thinking for the modern workplace.",
    instructor_email: "demo@skillforge.com",
    instructor_name: "Robert Kim",
    category: "business",
    difficulty: "intermediate",
    status: "published",
    enrollment_count: 19,
    rating: 4.7,
    tags: [],
    created_date: "2026-03-05",
  },
  {
    id: "c6",
    title: "Introduction to Music Theory",
    description:
      "Learn the fundamentals of music theory including scales, chords, and rhythm.",
    instructor_email: "demo@skillforge.com",
    instructor_name: "Linda Brooks",
    category: "music",
    difficulty: "beginner",
    status: "published",
    enrollment_count: 21,
    rating: 4.4,
    tags: [],
    created_date: "2026-03-06",
  },
];

export const MOCK_ENROLLMENTS = [
  {
    id: "e1",
    course_id: "c1",
    course_title: "Full-Stack Web Development",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    status: "in_progress",
    progress: 65,
    created_date: "2026-03-10",
  },
  {
    id: "e2",
    course_id: "c2",
    course_title: "UI/UX Design Fundamentals",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    status: "completed",
    progress: 100,
    rating: 5,
    completed_date: "2026-03-20",
    created_date: "2026-03-05",
  },
  {
    id: "e3",
    course_id: "c3",
    course_title: "Data Science with Python",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    status: "enrolled",
    progress: 10,
    created_date: "2026-03-25",
  },
];

export const MOCK_ASSESSMENTS = [
  {
    id: "a1",
    title: "React Fundamentals Quiz",
    description: "Test your knowledge of React hooks, state, and lifecycle.",
    course_id: "c1",
    instructor_email: "demo@skillforge.com",
    questions: [
      {
        question: "What hook is used for side effects?",
        options: ["useState", "useEffect", "useContext", "useRef"],
        correct_answer: 1,
        points: 10,
      },
      {
        question: "What does JSX stand for?",
        options: [
          "JavaScript XML",
          "Java Syntax Extension",
          "JSON XML",
          "JavaScript Extension",
        ],
        correct_answer: 0,
        points: 10,
      },
    ],
    time_limit_minutes: 30,
    passing_score: 70,
    status: "published",
    proctoring_enabled: false,
  },
  {
    id: "a2",
    title: "UI/UX Design Principles",
    description: "Assess your understanding of design fundamentals.",
    course_id: "c2",
    instructor_email: "demo@skillforge.com",
    questions: [
      {
        question: "What is the primary goal of UX design?",
        options: [
          "Make it look pretty",
          "Improve user satisfaction",
          "Reduce development cost",
          "Increase page load speed",
        ],
        correct_answer: 1,
        points: 10,
      },
      {
        question: "What does wireframing help with?",
        options: ["Coding", "Visual layout planning", "Database design", "SEO"],
        correct_answer: 1,
        points: 10,
      },
    ],
    time_limit_minutes: 20,
    passing_score: 70,
    status: "published",
    proctoring_enabled: false,
  },
  {
    id: "a3",
    title: "Python Data Basics",
    description: "Test your Python and data science fundamentals.",
    course_id: "c3",
    instructor_email: "demo@skillforge.com",
    questions: [
      {
        question: "Which library is used for data manipulation in Python?",
        options: ["NumPy", "Pandas", "Matplotlib", "Scikit-learn"],
        correct_answer: 1,
        points: 10,
      },
      {
        question: "What is a DataFrame?",
        options: [
          "A Python class",
          "A 2D labeled data structure",
          "A graph type",
          "A machine learning model",
        ],
        correct_answer: 1,
        points: 10,
      },
    ],
    time_limit_minutes: 25,
    passing_score: 70,
    status: "published",
    proctoring_enabled: false,
  },
];

export const MOCK_ASSESSMENT_RESULTS = [
  {
    id: "ar1",
    assessment_id: "a2",
    assessment_title: "UI/UX Design Principles",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    answers: [
      { question_index: 0, selected_answer: 1 },
      { question_index: 1, selected_answer: 1 },
    ],
    score: 20,
    total_points: 20,
    percentage: 100,
    passed: true,
    flags: [],
    time_taken_minutes: 12,
  },
  {
    id: "ar2",
    assessment_id: "a1",
    assessment_title: "React Fundamentals Quiz",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    answers: [
      { question_index: 0, selected_answer: 1 },
      { question_index: 1, selected_answer: 0 },
    ],
    score: 20,
    total_points: 20,
    percentage: 100,
    passed: true,
    flags: [],
    time_taken_minutes: 18,
  },
];

export const MOCK_CERTIFICATES = [
  {
    id: "cert1",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    course_id: "c2",
    course_title: "UI/UX Design Fundamentals",
    verification_code: "CERT-SK68-UIUX-2026",
    issue_date: "2026-03-20",
    issuer_name: "SkillForge",
    skills_certified: ["UI Design", "UX Research", "Figma", "Prototyping"],
    status: "active",
  },
  {
    id: "cert2",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    course_id: "c4",
    course_title: "Digital Marketing Strategy",
    verification_code: "CERT-SK68-MKT-2026",
    issue_date: "2026-02-10",
    issuer_name: "SkillForge",
    skills_certified: ["SEO", "Content Marketing", "Social Media", "Analytics"],
    status: "active",
  },
];

export const MOCK_JOBS = [
  {
    id: "j1",
    title: "Frontend Engineer",
    company_name: "TechCorp",
    company_email: "hr@techcorp.com",
    description:
      "Build beautiful, responsive UIs using React and TypeScript. Work with a cross-functional team to ship features fast.",
    type: "full_time",
    location: "San Francisco, CA",
    salary_range: "$100k–$130k",
    required_skills: ["React", "TypeScript", "CSS"],
    status: "open",
    application_count: 12,
    deadline: "2026-05-01",
    created_date: "2026-04-01",
  },
  {
    id: "j2",
    title: "Data Analyst Intern",
    company_name: "DataViz Inc",
    company_email: "jobs@dataviz.com",
    description:
      "Analyze large datasets and build dashboards. Great opportunity for students.",
    type: "internship",
    location: "Remote",
    salary_range: "$20/hr",
    required_skills: ["Python", "SQL", "Tableau"],
    status: "open",
    application_count: 5,
    deadline: "2026-04-20",
    created_date: "2026-04-02",
  },
  {
    id: "j3",
    title: "UX Designer",
    company_name: "DesignLab",
    company_email: "team@designlab.io",
    description:
      "Create wireframes, prototypes, and conduct user research for our product suite.",
    type: "full_time",
    location: "New York, NY",
    salary_range: "$90k–$110k",
    required_skills: ["Figma", "User Research", "Prototyping"],
    status: "open",
    application_count: 8,
    deadline: "2026-05-15",
    created_date: "2026-04-03",
  },
  {
    id: "j4",
    title: "Marketing Specialist",
    company_name: "GrowthHQ",
    company_email: "hire@growthhq.com",
    description:
      "Drive content strategy, SEO, and social media growth for our SaaS platform.",
    type: "remote",
    location: "Remote",
    salary_range: "$70k–$85k",
    required_skills: ["SEO", "Content Writing", "Analytics"],
    status: "open",
    application_count: 3,
    deadline: "2026-04-30",
    created_date: "2026-04-04",
  },
];

export const MOCK_EVENTS = [
  {
    id: "ev1",
    title: "React Workshop: Building Modern UIs",
    description:
      "Hands-on workshop covering React hooks, state management, and component patterns.",
    organizer_email: "demo@skillforge.com",
    organizer_name: "Sarah Chen",
    type: "workshop",
    date: "2026-04-15T14:00:00",
    end_date: "2026-04-15T17:00:00",
    is_virtual: true,
    meeting_link: "https://meet.example.com/react-workshop",
    max_attendees: 50,
    registration_count: 32,
    status: "upcoming",
    tags: [],
    created_date: "2026-03-20",
  },
  {
    id: "ev2",
    title: "Tech Career Fair 2026",
    description:
      "Meet top employers, attend panels, and network with industry professionals.",
    organizer_email: "demo@skillforge.com",
    organizer_name: "SkillForge Team",
    type: "conference",
    date: "2026-04-22T09:00:00",
    end_date: "2026-04-22T18:00:00",
    is_virtual: false,
    location: "Convention Center, San Francisco",
    max_attendees: 500,
    registration_count: 210,
    status: "upcoming",
    tags: [],
    created_date: "2026-03-21",
  },
  {
    id: "ev3",
    title: "Python for Beginners Meetup",
    description:
      "Casual meetup for Python beginners. Bring your laptop and questions!",
    organizer_email: "demo@skillforge.com",
    organizer_name: "Dr. James Park",
    type: "meetup",
    date: "2026-04-10T18:00:00",
    end_date: "2026-04-10T20:00:00",
    is_virtual: true,
    meeting_link: "https://meet.example.com/python-meetup",
    max_attendees: 30,
    registration_count: 18,
    status: "upcoming",
    tags: [],
    created_date: "2026-03-22",
  },
  {
    id: "ev4",
    title: "Design Systems Hackathon",
    description:
      "48-hour hackathon to build innovative design system components and tools.",
    organizer_email: "demo@skillforge.com",
    organizer_name: "Alex Rivera",
    type: "hackathon",
    date: "2026-05-01T09:00:00",
    end_date: "2026-05-03T09:00:00",
    is_virtual: true,
    meeting_link: "https://meet.example.com/hackathon",
    max_attendees: 100,
    registration_count: 45,
    status: "upcoming",
    tags: [],
    created_date: "2026-03-23",
  },
];

export const MOCK_COMMUNITIES = [
  {
    id: "com1",
    name: "React Developers",
    description:
      "A community for React enthusiasts to share tips, projects, and learn together.",
    category: "programming",
    creator_email: "demo@skillforge.com",
    member_count: 128,
    visibility: "public",
    tags: [],
  },
  {
    id: "com2",
    name: "UX Research Hub",
    description:
      "Discuss UX research methods, share case studies, and improve your research skills.",
    category: "design",
    creator_email: "demo@skillforge.com",
    member_count: 67,
    visibility: "public",
    tags: [],
  },
  {
    id: "com3",
    name: "Startup Founders Circle",
    description:
      "Connect with fellow founders, share experiences, and get advice on building startups.",
    category: "business",
    creator_email: "demo@skillforge.com",
    member_count: 45,
    visibility: "public",
    tags: [],
  },
  {
    id: "com4",
    name: "Data Science Study Group",
    description:
      "Weekly study sessions, project collaborations, and knowledge sharing for data science.",
    category: "science",
    creator_email: "demo@skillforge.com",
    member_count: 89,
    visibility: "public",
    tags: [],
  },
];

export const MOCK_DISCUSSIONS = [
  {
    id: "d1",
    title: "Best practices for React state management in 2026?",
    content:
      "I have been debating between Redux Toolkit, Zustand, and Jotai. What are your thoughts on which one to use for large-scale apps?",
    author_email: "surafelkaleab68@gmail.com",
    author_name: "Surafel Kaleab",
    community_id: "com1",
    community_name: "React Developers",
    type: "question",
    likes: 14,
    replies_count: 5,
    tags: [],
    created_date: "2026-04-01T10:00:00",
  },
  {
    id: "d2",
    title: "Sharing my portfolio redesign — feedback welcome!",
    content:
      "After 3 weeks of work, I finally redesigned my portfolio using Figma and the new design tokens approach. Here is a link to the prototype...",
    author_email: "demo@skillforge.com",
    author_name: "Alex Rivera",
    community_id: "com1",
    community_name: "React Developers",
    type: "discussion",
    likes: 9,
    replies_count: 3,
    tags: [],
    created_date: "2026-03-30T12:00:00",
  },
  {
    id: "d3",
    title: "Upcoming study session on Pandas DataFrames",
    content:
      "We are hosting a virtual study session this Saturday. Come prepared with your questions!",
    author_email: "demo@skillforge.com",
    author_name: "Dr. James Park",
    community_id: "com4",
    community_name: "Data Science Study Group",
    type: "announcement",
    likes: 7,
    replies_count: 2,
    tags: [],
    created_date: "2026-03-28T09:00:00",
  },
];

export const MOCK_DISCUSSION_REPLIES = [
  {
    id: "dr1",
    discussion_id: "d1",
    author_email: "demo@skillforge.com",
    author_name: "Sarah Chen",
    content:
      "I personally prefer Zustand for its simplicity. Redux Toolkit is great for very large apps but adds boilerplate.",
    likes: 6,
    created_date: "2026-04-01T11:00:00",
  },
  {
    id: "dr2",
    discussion_id: "d1",
    author_email: "demo@skillforge.com",
    author_name: "Robert Kim",
    content:
      "Jotai is excellent if you want atomic state. Pairs very nicely with React Query for server state.",
    likes: 4,
    created_date: "2026-04-01T13:00:00",
  },
];

export const MOCK_COMMUNITY_MEMBERS = [
  {
    id: "cm1",
    community_id: "com1",
    community_name: "React Developers",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    role: "member",
  },
  {
    id: "cm2",
    community_id: "com1",
    community_name: "React Developers",
    user_email: "demo@skillforge.com",
    user_name: "Sarah Chen",
    role: "admin",
  },
  {
    id: "cm3",
    community_id: "com2",
    community_name: "UX Research Hub",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    role: "member",
  },
  {
    id: "cm4",
    community_id: "com4",
    community_name: "Data Science Study Group",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    role: "moderator",
  },
];

export const MOCK_EVENT_REGISTRATIONS = [
  {
    id: "er1",
    event_id: "ev1",
    event_title: "React Workshop: Building Modern UIs",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    status: "registered",
  },
  {
    id: "er2",
    event_id: "ev2",
    event_title: "Tech Career Fair 2026",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    status: "registered",
  },
];

export const MOCK_SKILL_PROFILES = [
  {
    id: "sp1",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    skill_name: "React",
    skill_type: "teaching",
    proficiency_level: "advanced",
    category: "programming",
    description:
      "I have been using React for 3+ years building production apps.",
    availability: "available",
  },
  {
    id: "sp2",
    user_email: "surafelkaleab68@gmail.com",
    user_name: "Surafel Kaleab",
    skill_name: "Machine Learning",
    skill_type: "learning",
    proficiency_level: "beginner",
    category: "science",
    description: "Looking to get into ML and data science.",
    availability: "available",
  },
  {
    id: "sp3",
    user_email: "demo@skillforge.com",
    user_name: "Sarah Chen",
    skill_name: "Node.js",
    skill_type: "teaching",
    proficiency_level: "expert",
    category: "programming",
    description: "Backend expert with 5+ years of Node.js experience.",
    availability: "available",
  },
  {
    id: "sp4",
    user_email: "demo@skillforge.com",
    user_name: "Dr. James Park",
    skill_name: "Python",
    skill_type: "teaching",
    proficiency_level: "expert",
    category: "science",
    description: "Data scientist specializing in Python and ML.",
    availability: "available",
  },
  {
    id: "sp5",
    user_email: "demo@skillforge.com",
    user_name: "Alex Rivera",
    skill_name: "Figma",
    skill_type: "teaching",
    proficiency_level: "advanced",
    category: "design",
    description: "UI/UX designer passionate about design systems.",
    availability: "available",
  },
];

export const MOCK_SKILL_MATCHES = [
  {
    id: "sm1",
    user_a_email: "surafelkaleab68@gmail.com",
    user_a_name: "Surafel Kaleab",
    user_b_email: "demo@skillforge.com",
    user_b_name: "Dr. James Park",
    skill_a_teaches: "React",
    skill_b_teaches: "Python",
    match_score: 88,
    status: "suggested",
  },
];

export const MOCK_MESSAGES = [
  {
    id: "msg1",
    sender_email: "demo@skillforge.com",
    sender_name: "Dr. James Park",
    receiver_email: "surafelkaleab68@gmail.com",
    content:
      "Hey! I saw we matched on skill exchange. I can teach you Python if you help me with React!",
    read: true,
    created_date: "2026-04-01T09:00:00",
  },
  {
    id: "msg2",
    sender_email: "surafelkaleab68@gmail.com",
    sender_name: "Surafel Kaleab",
    receiver_email: "demo@skillforge.com",
    content: "That sounds great! When are you free for our first session?",
    read: true,
    created_date: "2026-04-01T09:15:00",
  },
  {
    id: "msg3",
    sender_email: "demo@skillforge.com",
    sender_name: "Dr. James Park",
    receiver_email: "surafelkaleab68@gmail.com",
    content: "How about Saturday at 10am?",
    read: false,
    created_date: "2026-04-01T09:30:00",
  },
];

export const MOCK_COURSE_MATERIALS = [
  {
    id: "mat1",
    course_id: "c1",
    title: "Introduction to React",
    type: "video",
    content: "Overview of React fundamentals and the virtual DOM.",
    file_url: "",
    order: 0,
  },
  {
    id: "mat2",
    course_id: "c1",
    title: "Lecture Notes - Week 1",
    type: "document",
    content: "Comprehensive notes covering JSX, components, and props.",
    file_url: "",
    order: 1,
  },
  {
    id: "mat3",
    course_id: "c1",
    title: "Hooks Deep Dive",
    type: "video",
    content: "useState, useEffect, useContext and custom hooks explained.",
    file_url: "",
    order: 2,
  },
  {
    id: "mat4",
    course_id: "c2",
    title: "Design Thinking Overview",
    type: "document",
    content: "Introduction to the design thinking framework.",
    file_url: "",
    order: 0,
  },
  {
    id: "mat5",
    course_id: "c2",
    title: "Figma Basics Tutorial",
    type: "video",
    content: "Getting started with Figma for UI design.",
    file_url: "",
    order: 1,
  },
];

export const MOCK_JOB_APPLICATIONS = [];

export const MOCK_ALL_USERS = [
  {
    id: "user-1",
    email: "surafelkaleab68@gmail.com",
    full_name: "Surafel Kaleab",
    role: "admin",
  },
  {
    id: "user-2",
    email: "surafelkaleab38@gmail.com",
    full_name: "Surafel K",
    role: "user",
  },
  {
    id: "user-3",
    email: "demo@skillforge.com",
    full_name: "Sarah Chen",
    role: "mentor",
  },
];
