// ============ USERS ============
export const mockUsers = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "admin",
    status: "active",
    joinedDate: "2024-01-15",
    enrolledCourses: 3,
    certificates: 2,
    avatar: "AJ",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-02-20",
    enrolledCourses: 5,
    certificates: 3,
    avatar: "BS",
  },
  {
    id: 3,
    name: "Carol Williams",
    email: "carol@example.com",
    role: "user",
    status: "suspended",
    joinedDate: "2024-03-10",
    enrolledCourses: 1,
    certificates: 0,
    avatar: "CW",
  },
  {
    id: 4,
    name: "David Brown",
    email: "david@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-04-05",
    enrolledCourses: 7,
    certificates: 5,
    avatar: "DB",
  },
  {
    id: 5,
    name: "Eva Martinez",
    email: "eva@example.com",
    role: "admin",
    status: "active",
    joinedDate: "2024-05-12",
    enrolledCourses: 2,
    certificates: 1,
    avatar: "EM",
  },
  {
    id: 6,
    name: "Frank Lee",
    email: "frank@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-06-18",
    enrolledCourses: 4,
    certificates: 2,
    avatar: "FL",
  },
  {
    id: 7,
    name: "Grace Kim",
    email: "grace@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-07-22",
    enrolledCourses: 6,
    certificates: 4,
    avatar: "GK",
  },
  {
    id: 8,
    name: "Henry Davis",
    email: "henry@example.com",
    role: "user",
    status: "suspended",
    joinedDate: "2024-08-30",
    enrolledCourses: 0,
    certificates: 0,
    avatar: "HD",
  },
  {
    id: 9,
    name: "Isla Thompson",
    email: "isla@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-09-14",
    enrolledCourses: 3,
    certificates: 1,
    avatar: "IT",
  },
  {
    id: 10,
    name: "Jack Wilson",
    email: "jack@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-10-01",
    enrolledCourses: 2,
    certificates: 1,
    avatar: "JW",
  },
  {
    id: 11,
    name: "Karen Patel",
    email: "karen@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-11-05",
    enrolledCourses: 8,
    certificates: 6,
    avatar: "KP",
  },
  {
    id: 12,
    name: "Leo Garcia",
    email: "leo@example.com",
    role: "user",
    status: "active",
    joinedDate: "2024-12-10",
    enrolledCourses: 1,
    certificates: 0,
    avatar: "LG",
  },
];

// ============ COURSES ============
export const mockCourses = [
  {
    id: 1,
    title: "React Masterclass",
    category: "Development",
    instructor: "Alice Johnson",
    status: "published",
    enrollments: 342,
    rating: 4.8,
    createdDate: "2024-01-20",
    materials: 24,
  },
  {
    id: 2,
    title: "UX Design Fundamentals",
    category: "Design",
    instructor: "Bob Smith",
    status: "published",
    enrollments: 218,
    rating: 4.5,
    createdDate: "2024-02-15",
    materials: 18,
  },
  {
    id: 3,
    title: "Data Science with Python",
    category: "Data Science",
    instructor: "Carol Williams",
    status: "draft",
    enrollments: 0,
    rating: 0,
    createdDate: "2024-03-01",
    materials: 12,
  },
  {
    id: 4,
    title: "Cloud Architecture Basics",
    category: "Cloud",
    instructor: "David Brown",
    status: "published",
    enrollments: 156,
    rating: 4.6,
    createdDate: "2024-04-10",
    materials: 20,
  },
  {
    id: 5,
    title: "Machine Learning A-Z",
    category: "Data Science",
    instructor: "Eva Martinez",
    status: "published",
    enrollments: 489,
    rating: 4.9,
    createdDate: "2024-05-05",
    materials: 32,
  },
  {
    id: 6,
    title: "Mobile App Development",
    category: "Development",
    instructor: "Frank Lee",
    status: "archived",
    enrollments: 95,
    rating: 3.8,
    createdDate: "2024-06-20",
    materials: 15,
  },
  {
    id: 7,
    title: "Digital Marketing Strategy",
    category: "Marketing",
    instructor: "Grace Kim",
    status: "published",
    enrollments: 267,
    rating: 4.3,
    createdDate: "2024-07-15",
    materials: 22,
  },
  {
    id: 8,
    title: "Cybersecurity Essentials",
    category: "Security",
    instructor: "Henry Davis",
    status: "draft",
    enrollments: 0,
    rating: 0,
    createdDate: "2024-08-01",
    materials: 8,
  },
  {
    id: 9,
    title: "Product Management 101",
    category: "Business",
    instructor: "Isla Thompson",
    status: "published",
    enrollments: 178,
    rating: 4.4,
    createdDate: "2024-09-10",
    materials: 16,
  },
  {
    id: 10,
    title: "Advanced JavaScript",
    category: "Development",
    instructor: "Jack Wilson",
    status: "published",
    enrollments: 401,
    rating: 4.7,
    createdDate: "2024-10-05",
    materials: 28,
  },
];

// ============ ASSESSMENTS ============
export const mockAssessments = [
  {
    id: 1,
    title: "React Basics Quiz",
    course: "React Masterclass",
    status: "published",
    questions: 25,
    passingScore: 70,
    timeLimit: 30,
    proctoring: true,
    submissions: 210,
    passRate: 78,
  },
  {
    id: 2,
    title: "UX Design Midterm",
    course: "UX Design Fundamentals",
    status: "published",
    questions: 40,
    passingScore: 75,
    timeLimit: 60,
    proctoring: false,
    submissions: 145,
    passRate: 65,
  },
  {
    id: 3,
    title: "Python Data Structures",
    course: "Data Science with Python",
    status: "draft",
    questions: 30,
    passingScore: 65,
    timeLimit: 45,
    proctoring: true,
    submissions: 0,
    passRate: 0,
  },
  {
    id: 4,
    title: "Cloud Certification Prep",
    course: "Cloud Architecture Basics",
    status: "published",
    questions: 50,
    passingScore: 80,
    timeLimit: 90,
    proctoring: true,
    submissions: 98,
    passRate: 52,
  },
  {
    id: 5,
    title: "ML Final Exam",
    course: "Machine Learning A-Z",
    status: "closed",
    questions: 60,
    passingScore: 75,
    timeLimit: 120,
    proctoring: true,
    submissions: 320,
    passRate: 71,
  },
  {
    id: 6,
    title: "JavaScript Advanced Test",
    course: "Advanced JavaScript",
    status: "published",
    questions: 35,
    passingScore: 70,
    timeLimit: 45,
    proctoring: false,
    submissions: 275,
    passRate: 82,
  },
];

export const mockAssessmentResults = [
  {
    id: 1,
    assessmentId: 1,
    student: "Bob Smith",
    score: 88,
    passed: true,
    submittedDate: "2024-11-20",
  },
  {
    id: 2,
    assessmentId: 1,
    student: "David Brown",
    score: 62,
    passed: false,
    submittedDate: "2024-11-21",
  },
  {
    id: 3,
    assessmentId: 1,
    student: "Grace Kim",
    score: 95,
    passed: true,
    submittedDate: "2024-11-22",
  },
  {
    id: 4,
    assessmentId: 2,
    student: "Frank Lee",
    score: 73,
    passed: false,
    submittedDate: "2024-11-25",
  },
  {
    id: 5,
    assessmentId: 2,
    student: "Karen Patel",
    score: 89,
    passed: true,
    submittedDate: "2024-11-26",
  },
  {
    id: 6,
    assessmentId: 4,
    student: "Jack Wilson",
    score: 81,
    passed: true,
    submittedDate: "2024-12-01",
  },
  {
    id: 7,
    assessmentId: 5,
    student: "Isla Thompson",
    score: 77,
    passed: true,
    submittedDate: "2024-12-05",
  },
  {
    id: 8,
    assessmentId: 6,
    student: "Leo Garcia",
    score: 55,
    passed: false,
    submittedDate: "2024-12-10",
  },
];

// ============ CERTIFICATES ============
export const mockCertificates = [
  {
    id: 1,
    user: "Bob Smith",
    course: "React Masterclass",
    issuedDate: "2024-06-15",
    verificationCode: "CERT-RF8K2M",
    status: "active",
  },
  {
    id: 2,
    user: "David Brown",
    course: "Machine Learning A-Z",
    issuedDate: "2024-07-20",
    verificationCode: "CERT-ML3P9X",
    status: "active",
  },
  {
    id: 3,
    user: "Grace Kim",
    course: "UX Design Fundamentals",
    issuedDate: "2024-08-10",
    verificationCode: "CERT-UX7N4Q",
    status: "active",
  },
  {
    id: 4,
    user: "Karen Patel",
    course: "Advanced JavaScript",
    issuedDate: "2024-09-05",
    verificationCode: "CERT-JS2W6T",
    status: "revoked",
  },
  {
    id: 5,
    user: "Alice Johnson",
    course: "Cloud Architecture Basics",
    issuedDate: "2024-10-12",
    verificationCode: "CERT-CL5H8R",
    status: "active",
  },
  {
    id: 6,
    user: "Eva Martinez",
    course: "Digital Marketing Strategy",
    issuedDate: "2024-11-01",
    verificationCode: "CERT-DM9K1V",
    status: "active",
  },
  {
    id: 7,
    user: "Frank Lee",
    course: "Product Management 101",
    issuedDate: "2024-11-20",
    verificationCode: "CERT-PM4J7Y",
    status: "active",
  },
  {
    id: 8,
    user: "Bob Smith",
    course: "Advanced JavaScript",
    issuedDate: "2024-12-01",
    verificationCode: "CERT-JS8L3N",
    status: "active",
  },
];

// ============ JOBS ============
export const mockJobs = [
  {
    id: 1,
    title: "Senior React Developer",
    company: "TechCorp",
    type: "Full-time",
    location: "Remote",
    status: "active",
    applications: 45,
    postedDate: "2024-10-01",
  },
  {
    id: 2,
    title: "UX Designer",
    company: "DesignHub",
    type: "Full-time",
    location: "New York",
    status: "active",
    applications: 32,
    postedDate: "2024-10-15",
  },
  {
    id: 3,
    title: "Data Analyst Intern",
    company: "DataFlow",
    type: "Internship",
    location: "San Francisco",
    status: "pending",
    applications: 18,
    postedDate: "2024-11-01",
  },
  {
    id: 4,
    title: "Cloud Engineer",
    company: "CloudNine",
    type: "Contract",
    location: "Remote",
    status: "active",
    applications: 27,
    postedDate: "2024-11-10",
  },
  {
    id: 5,
    title: "Product Manager",
    company: "InnovateCo",
    type: "Full-time",
    location: "London",
    status: "closed",
    applications: 56,
    postedDate: "2024-09-20",
  },
  {
    id: 6,
    title: "Marketing Specialist",
    company: "BrandWise",
    type: "Part-time",
    location: "Chicago",
    status: "pending",
    applications: 12,
    postedDate: "2024-11-25",
  },
  {
    id: 7,
    title: "ML Engineer",
    company: "AI Labs",
    type: "Full-time",
    location: "Remote",
    status: "active",
    applications: 38,
    postedDate: "2024-12-01",
  },
];

export const mockApplications = [
  {
    id: 1,
    jobId: 1,
    applicant: "Bob Smith",
    status: "reviewing",
    appliedDate: "2024-10-05",
    coverLetter: "I'm excited about this opportunity...",
  },
  {
    id: 2,
    jobId: 1,
    applicant: "David Brown",
    status: "shortlisted",
    appliedDate: "2024-10-07",
    coverLetter: "With 5 years of React experience...",
  },
  {
    id: 3,
    jobId: 1,
    applicant: "Grace Kim",
    status: "accepted",
    appliedDate: "2024-10-10",
    coverLetter: "I believe my skills align perfectly...",
  },
  {
    id: 4,
    jobId: 2,
    applicant: "Frank Lee",
    status: "rejected",
    appliedDate: "2024-10-20",
    coverLetter: "As a passionate designer...",
  },
  {
    id: 5,
    jobId: 2,
    applicant: "Karen Patel",
    status: "reviewing",
    appliedDate: "2024-10-22",
    coverLetter: "I have extensive UX experience...",
  },
  {
    id: 6,
    jobId: 4,
    applicant: "Jack Wilson",
    status: "shortlisted",
    appliedDate: "2024-11-15",
    coverLetter: "Cloud infrastructure is my forte...",
  },
  {
    id: 7,
    jobId: 7,
    applicant: "Leo Garcia",
    status: "reviewing",
    appliedDate: "2024-12-05",
    coverLetter: "I'm passionate about machine learning...",
  },
];

// ============ COMMUNITIES ============
export const mockCommunities = [
  {
    id: 1,
    name: "React Enthusiasts",
    category: "Development",
    visibility: "public",
    members: 1245,
    discussions: 89,
    createdDate: "2024-01-10",
  },
  {
    id: 2,
    name: "Design Thinking Hub",
    category: "Design",
    visibility: "public",
    members: 876,
    discussions: 54,
    createdDate: "2024-02-15",
  },
  {
    id: 3,
    name: "Data Science Network",
    category: "Data Science",
    visibility: "private",
    members: 543,
    discussions: 32,
    createdDate: "2024-03-20",
  },
  {
    id: 4,
    name: "Cloud Practitioners",
    category: "Cloud",
    visibility: "public",
    members: 432,
    discussions: 28,
    createdDate: "2024-04-25",
  },
  {
    id: 5,
    name: "Career Growth Circle",
    category: "Career",
    visibility: "public",
    members: 2100,
    discussions: 112,
    createdDate: "2024-05-01",
  },
  {
    id: 6,
    name: "AI Research Group",
    category: "Data Science",
    visibility: "private",
    members: 298,
    discussions: 45,
    createdDate: "2024-06-10",
  },
];

export const mockDiscussions = [
  {
    id: 1,
    communityId: 1,
    title: "Best practices for React hooks",
    author: "Bob Smith",
    replies: 23,
    createdDate: "2024-11-01",
    flagged: false,
  },
  {
    id: 2,
    communityId: 1,
    title: "React 19 new features discussion",
    author: "Grace Kim",
    replies: 45,
    createdDate: "2024-11-15",
    flagged: false,
  },
  {
    id: 3,
    communityId: 2,
    title: "Figma vs Sketch in 2024",
    author: "Frank Lee",
    replies: 18,
    createdDate: "2024-11-20",
    flagged: true,
  },
  {
    id: 4,
    communityId: 3,
    title: "Python vs R for data analysis",
    author: "Eva Martinez",
    replies: 31,
    createdDate: "2024-12-01",
    flagged: false,
  },
  {
    id: 5,
    communityId: 5,
    title: "Spam post - buy cheap products",
    author: "Henry Davis",
    replies: 2,
    createdDate: "2024-12-05",
    flagged: true,
  },
];

// ============ EVENTS ============
export const mockEvents = [
  {
    id: 1,
    title: "React Conference 2025",
    type: "Conference",
    date: "2025-03-15",
    organizer: "Alice Johnson",
    registrations: 450,
    status: "upcoming",
    location: "Virtual",
  },
  {
    id: 2,
    title: "UX Design Workshop",
    type: "Workshop",
    date: "2025-02-20",
    organizer: "Bob Smith",
    registrations: 80,
    status: "upcoming",
    location: "New York",
  },
  {
    id: 3,
    title: "Data Science Meetup",
    type: "Meetup",
    date: "2024-12-10",
    organizer: "Eva Martinez",
    registrations: 120,
    status: "completed",
    location: "San Francisco",
  },
  {
    id: 4,
    title: "Cloud Summit",
    type: "Conference",
    date: "2025-04-05",
    organizer: "David Brown",
    registrations: 280,
    status: "pending",
    location: "Virtual",
  },
  {
    id: 5,
    title: "Career Fair 2025",
    type: "Fair",
    date: "2025-05-10",
    organizer: "Grace Kim",
    registrations: 560,
    status: "upcoming",
    location: "Chicago",
  },
  {
    id: 6,
    title: "Hackathon Weekend",
    type: "Hackathon",
    date: "2025-01-25",
    organizer: "Jack Wilson",
    registrations: 200,
    status: "cancelled",
    location: "Virtual",
  },
];

// ============ SKILL EXCHANGE ============
export const mockSkillProfiles = [
  {
    id: 1,
    user: "Bob Smith",
    teaching: ["React", "JavaScript"],
    learning: ["Python", "Data Science"],
    rating: 4.7,
    sessions: 12,
  },
  {
    id: 2,
    user: "Grace Kim",
    teaching: ["UX Design", "Figma"],
    learning: ["React", "CSS"],
    rating: 4.9,
    sessions: 8,
  },
  {
    id: 3,
    user: "David Brown",
    teaching: ["Cloud Architecture", "AWS"],
    learning: ["Machine Learning"],
    rating: 4.5,
    sessions: 15,
  },
  {
    id: 4,
    user: "Eva Martinez",
    teaching: ["Data Science", "Python"],
    learning: ["UX Design", "Product Management"],
    rating: 4.8,
    sessions: 10,
  },
  {
    id: 5,
    user: "Frank Lee",
    teaching: ["Mobile Development", "Flutter"],
    learning: ["Cloud Architecture"],
    rating: 4.2,
    sessions: 6,
  },
  {
    id: 6,
    user: "Karen Patel",
    teaching: ["JavaScript", "TypeScript"],
    learning: ["AI", "Machine Learning"],
    rating: 4.6,
    sessions: 9,
  },
];

export const mockSkillMatches = [
  {
    id: 1,
    teacher: "Bob Smith",
    learner: "Grace Kim",
    skill: "React",
    status: "completed",
    rating: 5,
    feedback: "Excellent teacher, very patient!",
  },
  {
    id: 2,
    teacher: "Grace Kim",
    learner: "Bob Smith",
    skill: "UX Design",
    status: "accepted",
    rating: null,
    feedback: null,
  },
  {
    id: 3,
    teacher: "David Brown",
    learner: "Frank Lee",
    skill: "Cloud Architecture",
    status: "completed",
    rating: 4,
    feedback: "Great session, learned a lot.",
  },
  {
    id: 4,
    teacher: "Eva Martinez",
    learner: "Karen Patel",
    skill: "Data Science",
    status: "suggested",
    rating: null,
    feedback: null,
  },
  {
    id: 5,
    teacher: "Karen Patel",
    learner: "David Brown",
    skill: "TypeScript",
    status: "declined",
    rating: null,
    feedback: null,
  },
  {
    id: 6,
    teacher: "Bob Smith",
    learner: "Eva Martinez",
    skill: "JavaScript",
    status: "completed",
    rating: 5,
    feedback: "Very knowledgeable and helpful!",
  },
];

// ============ CHART DATA ============
export const userGrowthData = [
  { month: "Jan", users: 120 },
  { month: "Feb", users: 180 },
  { month: "Mar", users: 250 },
  { month: "Apr", users: 340 },
  { month: "May", users: 420 },
  { month: "Jun", users: 510 },
  { month: "Jul", users: 620 },
  { month: "Aug", users: 750 },
  { month: "Sep", users: 890 },
  { month: "Oct", users: 1050 },
  { month: "Nov", users: 1230 },
  { month: "Dec", users: 1450 },
];

export const enrollmentTrendsData = [
  { month: "Jan", enrollments: 45 },
  { month: "Feb", enrollments: 72 },
  { month: "Mar", enrollments: 98 },
  { month: "Apr", enrollments: 134 },
  { month: "May", enrollments: 165 },
  { month: "Jun", enrollments: 198 },
  { month: "Jul", enrollments: 230 },
  { month: "Aug", enrollments: 278 },
  { month: "Sep", enrollments: 310 },
  { month: "Oct", enrollments: 356 },
  { month: "Nov", enrollments: 402 },
  { month: "Dec", enrollments: 450 },
];

export const courseCategoryData = [
  { name: "Development", value: 35 },
  { name: "Design", value: 18 },
  { name: "Data Science", value: 22 },
  { name: "Cloud", value: 12 },
  { name: "Business", value: 8 },
  { name: "Marketing", value: 5 },
];

export const jobTypeData = [
  { name: "Full-time", value: 45 },
  { name: "Part-time", value: 15 },
  { name: "Contract", value: 20 },
  { name: "Internship", value: 12 },
  { name: "Freelance", value: 8 },
];

export const recentActivity = [
  {
    id: 1,
    type: "signup",
    message: "Leo Garcia joined the platform",
    time: "2 minutes ago",
    icon: "user",
  },
  {
    id: 2,
    type: "course",
    message: "New course submitted: Cybersecurity Essentials",
    time: "15 minutes ago",
    icon: "book",
  },
  {
    id: 3,
    type: "job",
    message: "ML Engineer position posted by AI Labs",
    time: "1 hour ago",
    icon: "briefcase",
  },
  {
    id: 4,
    type: "certificate",
    message: "Certificate issued to Bob Smith for Advanced JS",
    time: "2 hours ago",
    icon: "award",
  },
  {
    id: 5,
    type: "signup",
    message: "Jack Wilson joined the platform",
    time: "3 hours ago",
    icon: "user",
  },
  {
    id: 6,
    type: "event",
    message: "React Conference 2025 registration opened",
    time: "5 hours ago",
    icon: "calendar",
  },
  {
    id: 7,
    type: "community",
    message: "New community created: AI Research Group",
    time: "8 hours ago",
    icon: "users",
  },
  {
    id: 8,
    type: "course",
    message: "Machine Learning A-Z reached 489 enrollments",
    time: "12 hours ago",
    icon: "trending",
  },
];

// ============ ADMIN ROLES ============
export const PRIVILEGE_MODULES = [
  {
    module: "users",
    label: "User Management",
    actions: ["view", "create", "update", "delete", "suspend", "invite"],
  },
  {
    module: "courses",
    label: "Course Management",
    actions: ["view", "create", "update", "delete", "publish", "archive"],
  },
  {
    module: "assessments",
    label: "Assessment Management",
    actions: ["view", "create", "update", "delete", "close"],
  },
  {
    module: "certificates",
    label: "Certificate Management",
    actions: ["view", "revoke"],
  },
  {
    module: "jobs",
    label: "Job Management",
    actions: ["view", "create", "update", "delete", "approve", "reject"],
  },
  {
    module: "communities",
    label: "Community Management",
    actions: ["view", "update", "delete", "moderate"],
  },
  {
    module: "events",
    label: "Event Management",
    actions: ["view", "create", "update", "delete", "approve", "cancel"],
  },
  {
    module: "skill_exchange",
    label: "Skill Exchange",
    actions: ["view", "delete", "moderate"],
  },
  {
    module: "settings",
    label: "Platform Settings",
    actions: ["view", "update"],
  },
];

export const mockAdminRoles = [
  {
    id: 1,
    name: "Content Moderator",
    description: "Can manage courses, communities and events",
    email: "moderator@skillforge.com",
    status: "active",
    createdDate: "2024-10-01",
    privileges: {
      courses: ["view", "update", "publish", "archive"],
      communities: ["view", "update", "moderate"],
      events: ["view", "approve", "cancel"],
    },
  },
  {
    id: 2,
    name: "User Support Admin",
    description: "Handles user-related support and management",
    email: "support@skillforge.com",
    status: "active",
    createdDate: "2024-11-05",
    privileges: {
      users: ["view", "update", "suspend", "invite"],
      certificates: ["view", "revoke"],
    },
  },
  {
    id: 3,
    name: "Jobs Coordinator",
    description: "Reviews and approves job postings",
    email: "jobs@skillforge.com",
    status: "inactive",
    createdDate: "2024-12-01",
    privileges: {
      jobs: ["view", "approve", "reject", "delete"],
    },
  },
];

// ============ PLATFORM SETTINGS ============
export const defaultPlatformSettings = {
  platformName: "SkillForge",
  logo: "",
  primaryColor: "#6366f1",
  features: {
    jobBoard: true,
    skillExchange: true,
    communities: true,
    events: true,
    assessments: true,
    certificates: true,
  },
  categories: [
    "Development",
    "Design",
    "Data Science",
    "Cloud",
    "Business",
    "Marketing",
    "Security",
    "Career",
  ],
};
