# Generated by Django 6.0.4 on 2026-05-13 08:15

import uuid
from django.db import migrations, models


def seed_course_categories(apps, schema_editor):
    CourseCategory = apps.get_model('api', 'CourseCategory')
    categories = [
        ('Business', 'business'),
        ('Community', 'community'),
        ('Design', 'design'),
        ('Engineering', 'engineering'),
        ('Leadership', 'leadership'),
        ('Operations', 'operations'),
    ]

    for name, slug in categories:
        CourseCategory.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('organizations', models.ManyToManyField(blank=True, related_name='courses', to='api.organization')),
                ('categories', models.ManyToManyField(blank=True, related_name='courses', to='api.coursecategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RunPython(seed_course_categories, migrations.RunPython.noop),
    ]
