# Generated by Django 6.0.4 on 2026-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
