# Generated by Django 6.0.4 on 2026-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_courseenrollmentinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=20),
        ),
    ]
