# Generated by Django 6.0.4 on 2026-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='price_type',
        ),
    ]
